# This will publish the package to PyPi when pushing to master*.
#

name: Upload Python Package

on: workflow_dispatch

jobs:
  deploy:

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Bump version
      run: |
        poetry version patch
    - name: Commit and push version changes
      run: |
        ver="$(poetry version -s)"
        git config --global user.email "<>"
        git config --global user.name "Github-Actions"
        git config --global credential.helper store
        echo "https://${{secrets.GIT_USERNAME}}:${{secrets.GIT_TOKEN}}@github.com" > ~/.git-credentials
        git add .
        git commit -m "Release v${ver}"
        git push
        git tag "v${ver}"
        git push origin "refs/tags/v${ver}"
    - name: Build and publish
      run: |
        poetry publish --build -u "__token__" -p "${{ secrets.PYPI_TOKEN }}"
