# This will publish the package to PyPi when pushing to master*.
#

name: Upload Python Package

on: workflow_dispatch

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Bump version
      run: |
        poetry version patch
    - name: Commit and push version changes
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        ver="$(poetry version -s)"
        git config --global user.email "assessments@rhinoseucritylabs.com"
        git config --global user.name "rhinoassessments"
        git add .
        git commit -m "Release v${ver}"
        git push
        git tag "v${ver}"
        git push origin "refs/tags/v${ver}"
    - name: Build and publish
      run: |
        poetry publish --build -u "__token__" -p "${{ secrets.PYPI_TOKEN }}"
